/**
 * @file config.h
 * @brief TODO.
 *
 */

#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_WINDOW_TITLE "Heli-X Scene3D Tool"

#define CONFIG_WINDOW_WIDTH (800UL)
#define CONFIG_WINDOW_HEIGHT (800UL)

#define CONFIG_LINE_WIDTH (1.0f)

#define CONFIG_BACKGROUND_RGBA 0.1, 0.1, 0.1, 1.0
#define CONFIG_BACKGROUND_RGBA_INITIALIZER {CONFIG_BACKGROUND_RGBA}

#define CONFIG_VIEW_FOV_DEGREES (50.0)
#define CONFIG_VIEW_FOV_Z_NEAR (1.0)
#define CONFIG_VIEW_FOV_Z_FAR (400.0)
#define CONFIG_VIEW_UP_VECTOR 0, 1, 0
#define CONFIG_VIEW_UP_VECTOR_INITIALIZER {CONFIG_VIEW_UP_VECTOR}

#endif /* CONFIG_H */
